name: climate-vbd-uncertainty
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python>=3.10
  # Climepi package
  - climepi=0.4.1
  # General
  - numpy
  # Figures
  - bokeh>=3.6.3 #https://github.com/bokeh/bokeh/issues/14164
  - holoviews
  # Figure export
  - lxml
  - selenium
  - svgutils
  - webdriver-manager
  # Linting
  - ruff
  # Notebooks
  - ipykernel
  - jupyter_bokeh
  - nbconvert
  # Workflow
  - snakemake
  # Weather data
  - pip
  - pip:
    - meteostat