name: climate-disease-uncertainty
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  # Climepi package
  - climepi
  # General
  - numpy
  # Figures
  - bokeh<3.6 #https://github.com/bokeh/bokeh/issues/14164
  - holoviews
  # Figure export
  - lxml
  - selenium
  - svgutils
  - webdriver-manager
  # Linting
  - ruff
  # Notebooks
  - ipykernel
  - jupyter_bokeh
  - nbconvert
  # Workflow
  - snakemake
  # Weather data
  - pip
  - pip:
    - meteostat