name: climate-vbd-uncertainty
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=3.12
  # Climepi package
  - climepi=0.5
  # General
  - numpy=2.2
  # Figures
  - bokeh=3.7
  - holoviews=1.20
  # Figure export
  - lxml=5.4
  - selenium=4.32
  - svgutils=0.3
  - webdriver-manager=4.0
  # Linting
  - ruff=0.11
  # Notebooks
  - ipykernel=6.29
  - jupyter_bokeh=4.0
  - nbconvert=7.16
  # Workflow
  - snakemake=9.3
  # Weather data
  - pip
  - pip:
    - meteostat>=1.6,<1.7