name: climate-disease-uncertainty
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  # Climepi package
  - climepi
  # General
  - numpy
  # Figures
  - bokeh
  - holoviews
  # Figure export
  - lxml
  - selenium
  - svgutils
  - webdriver-manager
  # Linting
  - ruff
  # Notebooks
  - ipykernel
  - jupyter_bokeh
  - nbconvert
  # Workflow
  - snakemake