name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Hub (clean repo without figures)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          mkdir clean && cd clean
          rsync -av --exclude='figures/' ../ .
          git init
          git remote add origin https://will-s-hart:$HF_TOKEN@huggingface.co/spaces/will-s-hart/climate-vbd-uncertainty
          git checkout -b main
          echo "figures/" >> .gitignore
          git add .
          git commit -m "Clean push without binary files"
          git push -f origin main
